# Generated by Django 2.1.5 on 2019-10-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('parameter', models.CharField(db_column='PARAMETER', max_length=25, unique=True)),
                ('value', models.CharField(db_column='VALUE', max_length=255)),
            ],
            options={
                'db_table': 'cohort',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondDiagnosis',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cond_diagnosis',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondDiagnosisOrgans',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('diagnosis', models.ForeignKey(db_column='DIAGNOSIS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.CondDiagnosis')),
            ],
            options={
                'db_table': 'cond_diagnosis_organs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondLinkDiagnosisLabTests',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('diagnosis', models.ForeignKey(db_column='DIAGNOSIS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.CondDiagnosis')),
            ],
            options={
                'db_table': 'cond_link_diagnosis_lab_tests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondLinkDiagnosisSymptoms',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('diagnosis', models.ForeignKey(db_column='DIAGNOSIS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.CondDiagnosis')),
            ],
            options={
                'db_table': 'cond_link_diagnosis_symptoms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondSymptom',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cond_symptom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemoEducationLevelData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'demo_education_level_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemoEthnicityData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'demo_ethnicity_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemoOccupationData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'demo_occupation_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemoPregnancyData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'demo_pregnancy_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemoSexData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'demo_sex_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DemoWeightData',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'demo_weight_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DtAmount',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.FloatField(db_column='VALUE')),
            ],
            options={
                'db_table': 'dt_amount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DtAmountRange',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value1', models.FloatField(blank=True, db_column='VALUE1', null=True)),
                ('value2', models.FloatField(blank=True, db_column='VALUE2', null=True)),
            ],
            options={
                'db_table': 'dt_amount_range',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DtDate',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('year', models.TextField(db_column='YEAR')),
                ('month', models.PositiveSmallIntegerField(blank=True, db_column='MONTH', null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, db_column='DAY', null=True)),
                ('before_date', models.ForeignKey(blank=True, db_column='BEFORE_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate')),
            ],
            options={
                'db_table': 'dt_date',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DtIntRange',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('int1', models.IntegerField(blank=True, db_column='INT1', null=True)),
                ('int2', models.IntegerField(blank=True, db_column='INT2', null=True)),
            ],
            options={
                'db_table': 'dt_int_range',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DtPeriodOfTime',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('before_period', models.ForeignKey(blank=True, db_column='BEFORE_PERIOD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtPeriodOfTime')),
                ('end_date', models.ForeignKey(blank=True, db_column='END_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end', to='transfer.DtDate')),
            ],
            options={
                'db_table': 'dt_period_of_time',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamBiopsy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exam_biopsy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamCaciCondition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exam_caci_condition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamEssdaiDomain',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('visit_id', models.PositiveIntegerField(db_column='VISIT_ID')),
            ],
            options={
                'db_table': 'exam_essdai_domain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamLabTest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('outcome_term_id', models.PositiveIntegerField(blank=True, db_column='OUTCOME_TERM_ID', null=True)),
                ('normal_range', models.ForeignKey(blank=True, db_column='NORMAL_RANGE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtAmountRange')),
                ('outcome_amount', models.ForeignKey(blank=True, db_column='OUTCOME_AMOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtAmount')),
            ],
            options={
                'db_table': 'exam_lab_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamMedicalImagingTest',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'exam_medical_imaging_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionnaireScore',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, db_column='VALUE', null=True)),
                ('other_term_id', models.PositiveIntegerField(blank=True, db_column='OTHER_TERM_ID', null=True)),
            ],
            options={
                'db_table': 'exam_questionnaire_score',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntervChemotherapy',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interv_chemotherapy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntervMedication',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dosage', models.ForeignKey(blank=True, db_column='DOSAGE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtAmount')),
            ],
            options={
                'db_table': 'interv_medication',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IntervSurgery',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'interv_surgery',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LifestyleSmoking',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.ForeignKey(blank=True, db_column='AMOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtAmount')),
            ],
            options={
                'db_table': 'lifestyle_smoking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtherClinicalTrials',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'other_clinical_trials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtherFamilyHistory',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'other_family_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OtherHealthcareVisit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.ForeignKey(blank=True, db_column='DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate')),
            ],
            options={
                'db_table': 'other_healthcare_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('uid', models.CharField(db_column='UID', max_length=20)),
                ('cohort_inclusion_date', models.ForeignKey(blank=True, db_column='COHORT_INCLUSION_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inclusion', to='transfer.DtDate')),
                ('date_of_birth', models.ForeignKey(blank=True, db_column='DATE_OF_BIRTH_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dob', to='transfer.DtDate')),
                ('pss_diagnosis_date', models.ForeignKey(blank=True, db_column='PSS_DIAGNOSIS_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='diagnosis', to='transfer.DtDate')),
                ('pss_symptoms_onset_date', models.ForeignKey(blank=True, db_column='PSS_SYMPTOMS_ONSET_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='symptoms', to='transfer.DtDate')),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('patient', models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient')),
                ('visit_date', models.ForeignKey(db_column='VISIT_DATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate')),
            ],
            options={
                'db_table': 'patient_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocActivityLevel',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('activity_level', models.CharField(db_column='ACTIVITY_LEVEL', max_length=10)),
                ('value', models.PositiveSmallIntegerField(db_column='VALUE')),
            ],
            options={
                'db_table': 'voc_activity_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocAnaPattern',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
            ],
            options={
                'db_table': 'voc_ana_pattern',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocAssessment',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocAssessment')),
            ],
            options={
                'db_table': 'voc_assessment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocBiopsy',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocBiopsy')),
            ],
            options={
                'db_table': 'voc_biopsy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocBmiClass',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
            ],
            options={
                'db_table': 'voc_bmi_class',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocCaciCondition',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=20, unique=True)),
                ('condition', models.CharField(db_column='CONDITION', max_length=150)),
                ('score', models.PositiveSmallIntegerField(db_column='SCORE')),
            ],
            options={
                'db_table': 'voc_caci_condition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocConfirmation',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('acronym', models.CharField(db_column='ACRONYM', max_length=5, unique=True)),
            ],
            options={
                'db_table': 'voc_confirmation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocCryoType',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=255)),
            ],
            options={
                'db_table': 'voc_cryo_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocDirection',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('acronym', models.CharField(db_column='ACRONYM', max_length=5, unique=True)),
            ],
            options={
                'db_table': 'voc_direction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocEducationLevel',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('description', models.TextField(db_column='DESCRIPTION')),
            ],
            options={
                'db_table': 'voc_education_level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocEssdaiDomain',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('domain_name', models.CharField(db_column='DOMAIN_NAME', max_length=100)),
                ('domain_weight', models.PositiveSmallIntegerField(db_column='DOMAIN_WEIGHT')),
                ('exclude_activity_level', models.ForeignKey(blank=True, db_column='EXCLUDE_ACTIVITY_LEVEL', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocActivityLevel')),
            ],
            options={
                'db_table': 'voc_essdai_domain',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocEthnicity',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('description', models.TextField(db_column='DESCRIPTION')),
            ],
            options={
                'db_table': 'voc_ethnicity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocExamOutcomeType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('notes', models.CharField(db_column='NOTES', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'voc_exam_outcome_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocIpiRisk',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=255)),
            ],
            options={
                'db_table': 'voc_ipi_risk',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocLabTest',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=10, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=250)),
                ('range_notes', models.CharField(blank=True, db_column='RANGE_NOTES', max_length=200, null=True)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLabTest')),
            ],
            options={
                'db_table': 'voc_lab_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocLabTestType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
            ],
            options={
                'db_table': 'voc_lab_test_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocLymphomaOrgan',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLymphomaOrgan')),
            ],
            options={
                'db_table': 'voc_lymphoma_organ',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocLymphomaStage',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('description', models.TextField(db_column='DESCRIPTION')),
            ],
            options={
                'db_table': 'voc_lymphoma_stage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocMedicalCondition',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('aka', models.CharField(blank=True, db_column='AKA', max_length=250, null=True)),
                ('family_history', models.CharField(blank=True, db_column='FAMILY_HISTORY', max_length=1, null=True)),
                ('comorbidities', models.CharField(blank=True, db_column='COMORBIDITIES', max_length=1, null=True)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocMedicalCondition')),
            ],
            options={
                'db_table': 'voc_medical_condition',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocMedicalImagingTest',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('category_id', models.SmallIntegerField(db_column='CATEGORY_ID')),
                ('outcome_type', models.ForeignKey(blank=True, db_column='OUTCOME_TYPE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocExamOutcomeType')),
            ],
            options={
                'db_table': 'voc_medical_imaging_test',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocPerformanceStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=255)),
            ],
            options={
                'db_table': 'voc_performance_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocPharmDrug',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('aka', models.CharField(blank=True, db_column='AKA', max_length=255, null=True)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocPharmDrug')),
            ],
            options={
                'db_table': 'voc_pharm_drug',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocPregnancyOutcome',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('description', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocPregnancyOutcome')),
            ],
            options={
                'db_table': 'voc_pregnancy_outcome',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocQuestionnaire',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=200)),
                ('acronym', models.CharField(blank=True, db_column='ACRONYM', max_length=15, null=True, unique=True)),
                ('score_notes', models.CharField(blank=True, db_column='SCORE_NOTES', max_length=255, null=True)),
                ('score_normal_range', models.CharField(blank=True, db_column='SCORE_NORMAL_RANGE', max_length=255, null=True)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocQuestionnaire')),
                ('score_type', models.ForeignKey(blank=True, db_column='SCORE_TYPE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocExamOutcomeType')),
            ],
            options={
                'db_table': 'voc_questionnaire',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocRelativeDegree',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('value', models.CharField(db_column='VALUE', max_length=100)),
            ],
            options={
                'db_table': 'voc_relative_degree',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocSex',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
            ],
            options={
                'db_table': 'voc_sex',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocSmokingStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=250)),
            ],
            options={
                'db_table': 'voc_smoking_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocSpecialist',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
            ],
            options={
                'db_table': 'voc_specialist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocSymptomSign',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('category_id', models.PositiveSmallIntegerField(blank=True, db_column='CATEGORY_ID', null=True)),
                ('broader_term', models.ForeignKey(blank=True, db_column='BROADER_TERM_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocSymptomSign')),
            ],
            options={
                'db_table': 'voc_symptom_sign',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocUnit',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=10, unique=True)),
                ('expression', models.CharField(db_column='EXPRESSION', max_length=20, unique=True)),
                ('name', models.CharField(db_column='NAME', max_length=100)),
            ],
            options={
                'db_table': 'voc_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocVisitStatus',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('description', models.CharField(db_column='DESCRIPTION', max_length=255)),
            ],
            options={
                'db_table': 'voc_visit_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VocVisitType',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='CODE', max_length=15)),
                ('name', models.CharField(db_column='NAME', max_length=150)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=255, null=True)),
            ],
            options={
                'db_table': 'voc_visit_type',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='vocpharmdrug',
            name='dosage_unit',
            field=models.ForeignKey(blank=True, db_column='DOSAGE_UNIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocUnit'),
        ),
        migrations.AddField(
            model_name='voclabtest',
            name='lab_test_type',
            field=models.ForeignKey(blank=True, db_column='LAB_TEST_TYPE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLabTestType'),
        ),
        migrations.AddField(
            model_name='voclabtest',
            name='outcome_value',
            field=models.ForeignKey(blank=True, db_column='OUTCOME_VALUE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocExamOutcomeType'),
        ),
        migrations.AddField(
            model_name='voclabtest',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='UNIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocUnit'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='visit_status',
            field=models.ForeignKey(db_column='VISIT_STATUS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocVisitStatus'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='visit_type',
            field=models.ForeignKey(blank=True, db_column='VISIT_TYPE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocVisitType'),
        ),
        migrations.AddField(
            model_name='otherhealthcarevisit',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='otherhealthcarevisit',
            name='specialist',
            field=models.ForeignKey(db_column='SPECIALIST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocSpecialist'),
        ),
        migrations.AddField(
            model_name='otherhealthcarevisit',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='otherfamilyhistory',
            name='medical_condition',
            field=models.ForeignKey(db_column='MEDICAL_CONDITION_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocMedicalCondition'),
        ),
        migrations.AddField(
            model_name='otherfamilyhistory',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='otherfamilyhistory',
            name='relative_degree',
            field=models.ForeignKey(blank=True, db_column='RELATIVE_DEGREE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocRelativeDegree'),
        ),
        migrations.AddField(
            model_name='otherfamilyhistory',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='otherclinicaltrials',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='otherclinicaltrials',
            name='period',
            field=models.ForeignKey(blank=True, db_column='PERIOD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtPeriodOfTime'),
        ),
        migrations.AddField(
            model_name='otherclinicaltrials',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='lifestylesmoking',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='lifestylesmoking',
            name='period',
            field=models.ForeignKey(blank=True, db_column='PERIOD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtPeriodOfTime'),
        ),
        migrations.AddField(
            model_name='lifestylesmoking',
            name='status',
            field=models.ForeignKey(db_column='STATUS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocSmokingStatus'),
        ),
        migrations.AddField(
            model_name='lifestylesmoking',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='intervsurgery',
            name='due_to_pss',
            field=models.ForeignKey(blank=True, db_column='DUE_TO_PSS_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='intervsurgery',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='intervsurgery',
            name='surgery_date',
            field=models.ForeignKey(blank=True, db_column='SURGERY_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='intervsurgery',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='intervmedication',
            name='medication',
            field=models.ForeignKey(db_column='MEDICATION_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocPharmDrug'),
        ),
        migrations.AddField(
            model_name='intervmedication',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='intervmedication',
            name='period',
            field=models.ForeignKey(blank=True, db_column='PERIOD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtPeriodOfTime'),
        ),
        migrations.AddField(
            model_name='intervmedication',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='intervchemotherapy',
            name='due_to_pss',
            field=models.ForeignKey(blank=True, db_column='DUE_TO_PSS_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='intervchemotherapy',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='intervchemotherapy',
            name='period',
            field=models.ForeignKey(blank=True, db_column='PERIOD_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtPeriodOfTime'),
        ),
        migrations.AddField(
            model_name='intervchemotherapy',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='examquestionnairescore',
            name='assessment',
            field=models.ForeignKey(blank=True, db_column='ASSESSMENT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocAssessment'),
        ),
        migrations.AddField(
            model_name='examquestionnairescore',
            name='normal_range',
            field=models.ForeignKey(blank=True, db_column='NORMAL_RANGE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtIntRange'),
        ),
        migrations.AddField(
            model_name='examquestionnairescore',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='examquestionnairescore',
            name='questionnaire_date',
            field=models.ForeignKey(blank=True, db_column='QUESTIONNAIRE_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='examquestionnairescore',
            name='score',
            field=models.ForeignKey(db_column='SCORE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocQuestionnaire'),
        ),
        migrations.AddField(
            model_name='examquestionnairescore',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='exammedicalimagingtest',
            name='assessment',
            field=models.ForeignKey(db_column='ASSESSMENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocAssessment'),
        ),
        migrations.AddField(
            model_name='exammedicalimagingtest',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='exammedicalimagingtest',
            name='test',
            field=models.ForeignKey(db_column='TEST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocMedicalImagingTest'),
        ),
        migrations.AddField(
            model_name='exammedicalimagingtest',
            name='test_date',
            field=models.ForeignKey(blank=True, db_column='TEST_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='exammedicalimagingtest',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='examlabtest',
            name='outcome_assessment',
            field=models.ForeignKey(blank=True, db_column='OUTCOME_ASSESSMENT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocAssessment'),
        ),
        migrations.AddField(
            model_name='examlabtest',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='examlabtest',
            name='sample_date',
            field=models.ForeignKey(blank=True, db_column='SAMPLE_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='examlabtest',
            name='test',
            field=models.ForeignKey(db_column='TEST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLabTest'),
        ),
        migrations.AddField(
            model_name='examlabtest',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='examessdaidomain',
            name='activity_level',
            field=models.ForeignKey(db_column='ACTIVITY_LEVEL_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocActivityLevel'),
        ),
        migrations.AddField(
            model_name='examessdaidomain',
            name='domain',
            field=models.ForeignKey(db_column='DOMAIN_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocEssdaiDomain'),
        ),
        migrations.AddField(
            model_name='examessdaidomain',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='examessdaidomain',
            name='questionnaire_date',
            field=models.ForeignKey(blank=True, db_column='QUESTIONNAIRE_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='examcacicondition',
            name='caci',
            field=models.ForeignKey(db_column='CACI_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocCaciCondition'),
        ),
        migrations.AddField(
            model_name='examcacicondition',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='examcacicondition',
            name='questionnaire_date',
            field=models.ForeignKey(blank=True, db_column='QUESTIONNAIRE_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='examcacicondition',
            name='value',
            field=models.ForeignKey(db_column='VALUE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='examcacicondition',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='assessment',
            field=models.ForeignKey(blank=True, db_column='ASSESSMENT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocAssessment'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='biopsy',
            field=models.ForeignKey(db_column='BIOPSY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocBiopsy'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='biopsy_date',
            field=models.ForeignKey(db_column='BIOPSY_DATE_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='normal_range',
            field=models.ForeignKey(blank=True, db_column='NORMAL_RANGE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtAmountRange'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='outcome_amount',
            field=models.ForeignKey(blank=True, db_column='OUTCOME_AMOUNT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtAmount'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='outcome_check',
            field=models.ForeignKey(blank=True, db_column='OUTCOME_CHECK_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='test',
            field=models.ForeignKey(db_column='TEST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLabTest'),
        ),
        migrations.AddField(
            model_name='exambiopsy',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='dtperiodoftime',
            name='exact',
            field=models.ForeignKey(blank=True, db_column='EXACT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='end', to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='dtperiodoftime',
            name='start_date',
            field=models.ForeignKey(blank=True, db_column='START_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='start', to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='dtdate',
            name='op',
            field=models.ForeignKey(db_column='OP_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocDirection'),
        ),
        migrations.AddField(
            model_name='dtamountrange',
            name='unit',
            field=models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocUnit'),
        ),
        migrations.AddField(
            model_name='dtamount',
            name='unit',
            field=models.ForeignKey(db_column='UNIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocUnit'),
        ),
        migrations.AddField(
            model_name='demoweightdata',
            name='bmi_class',
            field=models.ForeignKey(db_column='BMI_CLASS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocBmiClass'),
        ),
        migrations.AddField(
            model_name='demoweightdata',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='demoweightdata',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='demosexdata',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='demosexdata',
            name='sex',
            field=models.ForeignKey(db_column='SEX_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocSex'),
        ),
        migrations.AddField(
            model_name='demosexdata',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='demopregnancydata',
            name='conception_date',
            field=models.ForeignKey(blank=True, db_column='CONCEPTION_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conception', to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='demopregnancydata',
            name='outcome',
            field=models.ForeignKey(db_column='OUTCOME_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocPregnancyOutcome'),
        ),
        migrations.AddField(
            model_name='demopregnancydata',
            name='outcome_date',
            field=models.ForeignKey(blank=True, db_column='OUTCOME_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='demopregnancydata',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='demopregnancydata',
            name='ss_concordant',
            field=models.ForeignKey(blank=True, db_column='SS_CONCORDANT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='demopregnancydata',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='demooccupationdata',
            name='loss_of_work_due_to_pss',
            field=models.ForeignKey(db_column='LOSS_OF_WORK_DUE_TO_PSS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocConfirmation'),
        ),
        migrations.AddField(
            model_name='demooccupationdata',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='demooccupationdata',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='demoethnicitydata',
            name='ethnicity',
            field=models.ForeignKey(db_column='ETHNICITY_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocEthnicity'),
        ),
        migrations.AddField(
            model_name='demoethnicitydata',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='demoethnicitydata',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='demoeducationleveldata',
            name='education_level',
            field=models.ForeignKey(db_column='EDUCATION_LEVEL_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocEducationLevel'),
        ),
        migrations.AddField(
            model_name='demoeducationleveldata',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='demoeducationleveldata',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='condsymptom',
            name='condition',
            field=models.ForeignKey(db_column='CONDITION_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocSymptomSign'),
        ),
        migrations.AddField(
            model_name='condsymptom',
            name='observe_date',
            field=models.ForeignKey(blank=True, db_column='OBSERVE_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='condsymptom',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='condsymptom',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
        migrations.AddField(
            model_name='condlinkdiagnosissymptoms',
            name='symptoms',
            field=models.ForeignKey(db_column='SYMPTOMS_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.CondSymptom'),
        ),
        migrations.AddField(
            model_name='condlinkdiagnosislabtests',
            name='lab_test',
            field=models.ForeignKey(db_column='LAB_TEST_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.ExamLabTest'),
        ),
        migrations.AddField(
            model_name='conddiagnosisorgans',
            name='organ',
            field=models.ForeignKey(db_column='ORGAN_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLymphomaOrgan'),
        ),
        migrations.AddField(
            model_name='conddiagnosis',
            name='condition',
            field=models.ForeignKey(db_column='CONDITION_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocMedicalCondition'),
        ),
        migrations.AddField(
            model_name='conddiagnosis',
            name='diagnosis_date',
            field=models.ForeignKey(blank=True, db_column='DIAGNOSIS_DATE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.DtDate'),
        ),
        migrations.AddField(
            model_name='conddiagnosis',
            name='patient',
            field=models.ForeignKey(db_column='PATIENT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.Patient'),
        ),
        migrations.AddField(
            model_name='conddiagnosis',
            name='performance_status',
            field=models.ForeignKey(blank=True, db_column='PERFORMANCE_STATUS_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocPerformanceStatus'),
        ),
        migrations.AddField(
            model_name='conddiagnosis',
            name='stage',
            field=models.ForeignKey(blank=True, db_column='STAGE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.VocLymphomaStage'),
        ),
        migrations.AddField(
            model_name='conddiagnosis',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
    ]
