# Generated by Django 2.1.5 on 2019-09-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambiopsy',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
    ]
