# Generated by Django 2.1.5 on 2019-09-17 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_auto_20190917_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examlabtest',
            name='visit',
            field=models.ForeignKey(db_column='VISIT_ID', on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
    ]
