# Generated by Django 2.1.5 on 2019-09-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0012_auto_20190919_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uid',
            field=models.CharField(db_column='UID', max_length=20),
        ),
    ]
