# Generated by Django 2.1.5 on 2019-09-20 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0013_auto_20190920_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestionnairescore',
            name='visit',
            field=models.ForeignKey(blank=True, db_column='VISIT_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transfer.PatientVisit'),
        ),
    ]
